//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barberiaEstetica.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTurnos
    {
        public int HistorialID { get; set; }
        public int TurnoID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string Accion { get; set; }
        public string Comentario { get; set; }
    
        public virtual Turnos Turnos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
