//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barberiaEstetica.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int NotificacionID { get; set; }
        public int TurnoID { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    
        public virtual Turnos Turnos { get; set; }
    }
}
